/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hangman;

import hangman.model.BodyPart;
import hangman.model.Hangman;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Hangman hangman = new Hangman();
        System.out.println(hangman.draw());
        Scanner scanner = new Scanner(System.in);
        String bodyPart;
        while (true){
            bodyPart=scanner.nextLine();
            if (bodyPart.equals("exit")) break;
            BodyPart bodyPart1 = BodyPart.of(bodyPart);
            System.out.println(hangman.chop(bodyPart1).draw());
        }
    }
}
