/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hangman;

import org.junit.Test;
import static org.junit.Assert.*;

public class HangmanApplicationTest {
    @Test public void testAppHasAGreeting() {
        HangmanApplication classUnderTest = new HangmanApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
