/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package command_game;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Scanner in = new Scanner(System.in);
        while (true){
        	String input = in.nextLine();
        	if ("Exit".equals(input)) return;
        	System.out.print("You entered "+input+" Please enter Exit to exit from this");
        }
    }
}
